### PR TITLE
Dev add shipping weight node

### PR DESCRIPTION
**Pull request by ChrGriffin**

### CODE REVIEW

**Comment by lukesnowden** [comment]
Not that is a major issue but could you remove the extra line which shouldn't be required?

```php
$weight = $this->safeCharEncodeText($weight);
```

There should be no chars anyway, I know its daft but if someone comes back at a later date they'll probably be think why its there, I know I would.


regards

**Comment by lukesnowden** [comment]
I'll do it

**Comment by ChrGriffin** [comment]
Sorry I couldn't get to it! I was pulled away to other things. Thanks for merging it, though! 👍

**Comment by lukesnowden** [comment]
👍 no worries

**Pull request merged**
